FROM tomcat:10.1.13-jdk11-temurin
RUN rm -rf /usr/local/tomcat/webapps/ROOT
RUN rm -rf /usr/local/tomcat/webapps/examples
ADD demo8-1.0-SNAPSHOT /usr/local/tomcat/webapps/

EXPOSE 8080
CMD ["catalina.sh", "run"]
